apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-health
  labels:
    app: my-app-health
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-health
  template:
    metadata:
      labels:
        app: my-app-health
    spec:
      containers:
      - name: heath-node
        image: minhnk/heath-node
        ports:
        - containerPort: 8080
      # livenessProbe:
      #   httpGet:
      #     path: /health
      #     port: 8080
      #   initialDelaySeconds: 3
      #   periodSeconds: 3